version: '3'

services:
  ivideon-server:
    image: croc/ivideon-server
    volumes:
      - '/etc/localtime:/etc/localtime'
      - './ivideon-data:/home/ivideon/.IvideonServer'
    ports:
      - '3389:3389'
    restart: unless-stopped
